<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <Version>1.8.1.4</Version>
    <FileVersion>1.8.1.4</FileVersion>
    <AssemblyVersion>1.8.1.4</AssemblyVersion>
    <OutputType>Library</OutputType>
    <AssemblyName>TerrariaSplit.WorldGuard.Payload</AssemblyName>
    <RootNamespace>TerrariaSplit.WorldGuard.Payload</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>7.3</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <ProjectReference Include="..\TerrariaSplit.Race.Determinism\TerrariaSplit.Race.Determinism.csproj" />
    <ProjectReference Include="..\TerrariaSplit.Race.InGame\TerrariaSplit.Race.InGame.csproj" />
  </ItemGroup>

</Project>
