<Project>

  <PropertyGroup>
    <BaseIntermediateOutputPath>Temp\obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>Temp\bin\</BaseOutputPath>
  </PropertyGroup>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Code\*.cs" />
    <Compile Include="Code\Diagnostics\*.cs" />
    <ProjectReference Include="..\src\TerrariaSplit.Application\TerrariaSplit.Application.csproj" />
    <ProjectReference Include="..\src\TerrariaSplit.Configuration\TerrariaSplit.Configuration.csproj" />
    <ProjectReference Include="..\src\TerrariaSplit.Domain\TerrariaSplit.Domain.csproj" />
    <ProjectReference Include="..\src\TerrariaSplit.Infrastructure\TerrariaSplit.Infrastructure.csproj" />
    <ProjectReference Include="..\src\TerrariaSplit.Infrastructure.Windows\TerrariaSplit.Infrastructure.Windows.csproj" />
    <ProjectReference Include="..\src\TerrariaSplit.Statistics\TerrariaSplit.Statistics.csproj" />
    <ProjectReference Include="..\src\TerrariaSplit.Storage\TerrariaSplit.Storage.csproj" />
    <ProjectReference Include="..\src\TerrariaSplit.Terraria\TerrariaSplit.Terraria.csproj" />
    <ProjectReference Include="..\src\TerrariaSplit.WinForms\TerrariaSplit.WinForms.csproj" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

</Project>
