<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Defaults\*.json" />
    <EmbeddedResource Include="Assets\Defaults\*.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerrariaSplit.Domain\TerrariaSplit.Domain.csproj" />
  </ItemGroup>

</Project>
