<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\TerrariaSplit\Configuration\**\*.cs" Link="Configuration\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\TerrariaSplit\Localization\**\*.cs" Link="Localization\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="GlobalUsings.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerrariaSplit.Domain\TerrariaSplit.Domain.csproj" />
  </ItemGroup>

</Project>
