<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\TerrariaSplit\Domain\**\*.cs" Link="Domain\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\TerrariaSplit\Models\**\*.cs" Link="Models\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="GlobalUsings.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

</Project>
