global using TerrariaSplit.Application;
global using TerrariaSplit.Application.Diagnostics;
global using TerrariaSplit.Application.Ports;
global using TerrariaSplit.Configuration;
global using TerrariaSplit.Domain;
global using TerrariaSplit.Domain.Formatting;
global using TerrariaSplit.Infrastructure;
global using TerrariaSplit.Localization;
global using TerrariaSplit.Models;
