namespace TerrariaSplit;

// Persisted, thread-safe pool of copied Terraria seed strings known to produce a pyramid
// for a single WorldGenSignature. The copied seed already carries size, difficulty, evil,
// special seed flags, and the real seed text generated by TerrariaServer.exe. The
// background fill service adds seeds; the workflow consumes the first. Whenever the
// active signature changes, the stored seeds are dropped because they no longer reproduce.
internal sealed class SeedPoolStore
{
    private static readonly string FilePath = Path.Combine(AppContext.BaseDirectory, "seed-pool", "seed-pool.json");

    private readonly object sync = new();
    private SeedPoolData data;

    public SeedPoolStore()
    {
        data = JsonFileStore.Read<SeedPoolData>(FilePath, "seed pool") ?? new SeedPoolData();
        data.Signature ??= string.Empty;
        data.Seeds ??= new List<string>();
    }

    public int Count(string signature)
    {
        lock (sync)
        {
            return SignatureMatches(signature) ? data.Seeds.Count(seed => !string.IsNullOrWhiteSpace(seed)) : 0;
        }
    }

    // Discards stored seeds when the signature no longer matches the active settings.
    public void EnsureSignature(string signature)
    {
        lock (sync)
        {
            if (!SignatureMatches(signature))
            {
                data = new SeedPoolData { Signature = signature };
                Persist();
            }
        }
    }

    public bool TryAdd(string signature, string seed)
    {
        string normalizedSeed = seed.Trim();
        if (string.IsNullOrWhiteSpace(normalizedSeed))
        {
            return false;
        }

        lock (sync)
        {
            if (!SignatureMatches(signature))
            {
                return false;
            }

            if (!data.Seeds.Any(existing => string.Equals(existing, normalizedSeed, StringComparison.Ordinal)))
            {
                data.Seeds.Add(normalizedSeed);
                Persist();
                return true;
            }
        }

        return false;
    }

    public bool TryPeekFirst(string signature, out string seed)
    {
        lock (sync)
        {
            if (SignatureMatches(signature))
            {
                while (data.Seeds.Count > 0)
                {
                    seed = data.Seeds[0];
                    if (!string.IsNullOrWhiteSpace(seed))
                    {
                        return true;
                    }

                    data.Seeds.RemoveAt(0);
                    Persist();
                }
            }
        }

        seed = string.Empty;
        return false;
    }

    // Removes the given seed only if it is still at the front, so a concurrent fill cannot
    // cause the wrong seed to be dropped.
    public void RemoveFirst(string signature, string seed)
    {
        lock (sync)
        {
            if (SignatureMatches(signature) &&
                data.Seeds.Count > 0 &&
                string.Equals(data.Seeds[0], seed, StringComparison.Ordinal))
            {
                data.Seeds.RemoveAt(0);
                Persist();
            }
        }
    }

    private bool SignatureMatches(string signature)
    {
        return string.Equals(data.Signature, signature, StringComparison.Ordinal);
    }

    private void Persist()
    {
        JsonFileStore.Write(FilePath, data, "seed pool");
    }

    internal sealed class SeedPoolData
    {
        public string? Signature { get; set; } = string.Empty;

        public List<string> Seeds { get; set; } = new();
    }
}
