namespace TerrariaSplit;

internal static class Localizer
{
    private static readonly Dictionary<string, string> Zh = new(StringComparer.OrdinalIgnoreCase)
    {
        { "TerrariaSplit Settings", "TerrariaSplit 设置" },
        { "OK", "确定" },
        { "Apply", "应用" },
        { "Cancel", "取消" },
        { "General", "常规" },
        { "Splits", "数据" },
        { "Data", "数据" },
        { "UI", "界面" },
        { "Colors", "颜色" },
        { "Sounds", "声音" },
        { "Hotkeys", "快捷键" },
        { "General Options", "常规选项" },
        { "Language", "语言" },
        { "Pause / Resume", "暂停 / 继续" },
        { "Reset at Menu", "在菜单时重置" },
        { "Mouse passthrough", "鼠标穿透" },
        { "Always on top", "置顶显示" },
        { "Practice mode", "练习模式" },
        { "Allow manual time editing", "允许手动修改时间" },
        { "Columns", "列" },
        { "Split display", "分段显示器" },
        { "Global scale %", "全局缩放 %" },
        { "Column", "列名" },
        { "Show", "显示" },
        { "Width", "宽度" },
        { "Font", "字体大小" },
        { "Bold", "粗体" },
        { "Icon", "图标" },
        { "Time", "时间" },
        { "Delta", "差值" },
        { "Timer", "计时器" },
        { "Main timer", "主计时器" },
        { "Offset X", "水平偏移" },
        { "Offset Y", "垂直偏移" },
        { "Part", "分段" },
        { "Section", "部分" },
        { "Main time", "主时间" },
        { "Before decimal", "小数点前" },
        { "Milliseconds", "毫秒" },
        { "After decimal", "小数点后" },
        { "Icon Style", "图标样式" },
        { "Light icons when BOSS defeated", "击败BOSS时点亮图标" },
        { "Enable defeated icon lighting", "启用击败点亮图标" },
        { "Current boss grayscale weaken %", "当前 BOSS 图标灰度额外削弱 %" },
        { "Current boss brightness boost %", "当前 BOSS 图标亮度额外增强 %" },
        { "Effects", "效果" },
        { "Current Split Highlight", "当前阶段突出显示" },
        { "Highlight current split", "突出显示当前分段" },
        { "Highlight current stage", "突出显示当前阶段" },
        { "Enable current split highlight", "启用当前阶段突出显示" },
        { "Current split scale %", "当前阶段放大比例 %" },
        { "Scale %", "放大比例 %" },
        { "Depth strength %", "景深强度 %" },
        { "BOSS Defeat", "BOSS 击败" },
        { "BOSS defeat animation", "BOSS击败动画" },
        { "Enable animation", "启用动画" },
        { "Animation duration seconds", "动画时长（秒）" },
        { "Show comparison", "显示对比" },
        { "Show comparison with reference time", "是否显示与参考时间的对比" },
        { "Rainbow outline", "炫彩描边" },
        { "Outline when faster than reference", "速度快于参考值时的描边" },
        { "Outline thickness %", "描边厚度 %" },
        { "None", "无" },
        { "Neon", "霓虹" },
        { "Rainbow", "炫彩" },
        { "Aurora", "极光" },
        { "Gold", "鎏金" },
        { "Breathe", "呼吸" },
        { "Segment Best Highlight", "分段最佳突出显示" },
        { "Highlight best segment", "突出显示最佳分段" },
        { "Enable highlight", "启用突出显示" },
        { "Effect", "效果" },
        { "Cumulative time", "累计时间" },
        { "Segment comparison", "分段时间比较" },
        { "Rainbow outline thickness %", "炫彩描边厚度 %" },
        { "Unlit grayscale %", "未击败时图标灰度 %" },
        { "Unlit brightness %", "未击败时图标亮度 %" },
        { "BOSS Icons", "BOSS 图标" },
        { "Choose BOSS Icon", "选择 BOSS 图标" },
        { "empty = bundled icon", "留空 = 默认图标" },
        { "Browse", "浏览" },
        { "Reference Data", "参考数据" },
        { "Personal Best Data", "个人累计最佳" },
        { "new group name", "新组名" },
        { "Add", "添加" },
        { "Delete", "删除" },
        { "Active group", "当前组" },
        { "Text Colors", "文字颜色" },
        { "Reference text", "参考时间文字" },
        { "Reference", "参考" },
        { "Reference time", "参考时间" },
        { "Reference run", "参考局" },
        { "Selected run", "选择一局" },
        { "Personal best", "个人累计最佳" },
        { "Personal Cumulative Best", "个人累计最佳" },
        { "Personal segment best", "个人分段最佳" },
        { "Personal Data", "个人数据" },
        { "Auto update personal data", "自动更新个人数据" },
        { "Segment time", "本段用时" },
        { "Split time", "累计时间" },
        { "Reference time column", "参考累计时间" },
        { "Selected run time column", "该局累计时间" },
        { "Personal best time column", "个人最佳累计时间" },
        { "Reference segment time column", "参考分段时间" },
        { "Selected run segment time column", "该局分段时间" },
        { "Personal best segment time column", "个人最佳分段时间" },
        { "Reference segment", "参考分段时间" },
        { "Personal segment", "该局分段时间" },
        { "Personal best segment", "个人最佳分段时间" },
        { "Active reference text", "当前目标时间文字" },
        { "Completed split text", "已完成分段文字" },
        { "Delta ahead text", "差值领先文字" },
        { "Delta behind text", "差值落后文字" },
        { "Delta even text", "差值持平文字" },
        { "Timer text", "计时文字" },
        { "Timer ahead text", "计时领先文字" },
        { "Timer behind text", "计时落后文字" },
        { "Timer record text", "计时破纪录文字" },
        { "Timer paused text", "计时暂停文字" },
        { "Pause sound", "暂停声音" },
        { "Reset sound", "重置声音" },
        { "Split: total behind, segment behind", "Split：总时间慢，分段慢" },
        { "Split: total behind, segment not behind", "Split：总时间慢，分段不慢" },
        { "Split: total not behind, segment behind", "Split：总时间不慢，分段慢" },
        { "Split: total not behind, segment not behind", "Split：总时间不慢，分段不慢" },
        { "Split reached: total slower than reference, segment slower than PB", "到达分段点：总时间慢于参考，分段慢于PB" },
        { "Split reached: total slower than reference, segment not slower than PB", "到达分段点：总时间慢于参考，分段不慢于PB" },
        { "Split reached: total not slower than reference, segment slower than PB", "到达分段点：总时间不慢于参考，分段慢于PB" },
        { "Split reached: total not slower than reference, segment not slower than PB", "到达分段点：总时间不慢于参考，分段不慢于PB" },
        { "Split: total slower, segment slower", "分段点：总慢于参考，分段慢于PB" },
        { "Split: total slower, segment not slower", "分段点：总慢于参考，分段不慢于PB" },
        { "Split: total not slower, segment slower", "分段点：总不慢于参考，分段慢于PB" },
        { "Split: total not slower, segment not slower", "分段点：总不慢于参考，分段不慢于PB" },
        { "Choose sound", "选择声音" },
        { "Clear", "清空" },
        { "BOSS Groups", "BOSS 分组" },
        { "BOSS route", "BOSS 顺序" },
        { "BOSS", "BOSS" },
        { "BOSS Group", "BOSS 分组" },
        { "Enabled", "启用" },
        { "Segment", "分组" },
        { "Group", "分组" },
        { "Settings...", "设置..." },
        { "Switch config", "切换配置" },
        { "No config files", "没有配置文件" },
        { "Statistics...", "统计信息..." },
        { "Statistics", "统计信息" },
        { "Last run", "上一局" },
        { "Best split", "历史最佳分段时间" },
        { "Fastest segment", "最快分段时间" },
        { "No splits", "没有分段" },
        { "Exit", "退出" },
        { "Edit total time", "编辑总计时间" },
        { "Edit split time", "编辑分段时间" },
        { "Skeletron", "骷髅王" },
        { "Wall of Flesh", "血肉墙" },
        { "Destroyer", "毁灭者" },
        { "Skeletron Prime", "机械骷髅王" },
        { "The Twins", "双子魔眼" },
        { "Plantera", "世纪之花" },
        { "Golem", "石巨人" },
        { "Lunatic Cultist", "拜月教徒" },
        { "Moon Lord", "月亮领主" },
        { "Mechanical Bosses", "机械三王" }
    };

    public static string Get(string key, AppSettings settings)
    {
        if (settings.Language == "中文" && Zh.TryGetValue(key, out string? value))
        {
            return value;
        }
        return key;
    }
}
