<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<FileVersion>3.0.0.0</FileVersion>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**;.build-check\**;.check\**;.verify\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\BossIcons\*.*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Assets\ReferenceTimes\*.*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="settings\settings.json" Link="Assets\DefaultSettings\settings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
